#!/bin/sh

set -euvx

curl -sLO https://raw.githubusercontent.com/rethink-neil/github-get/master/github-get
chmod +x github-get
./github-get https://github.com/richfelker/musl-cross-make
echo 'TARGET=x86_64-linux-musl' >musl-cross-make/config.mak
make -C musl-cross-make -j $(getconf _NPROCESSORS_ONLN) all
make -C musl-cross-make install
./github-get https://github.com/landley/toybox
export CROSS_COMPILE="x86_64-linux-musl-"
export PATH=${PWD}/musl-cross-make/output/bin:${PATH}
export CFLAGS="--static"
export LDFLAGS="--static"
make -C toybox defconfig
make -C toybox -j $(getconf _NPROCESSORS_ONLN) all
# PREFIX=/usr/local make -C toybox install
